### ISSUE TITLE
Specify Organisation in API

### ISSUE THREAD

**Issue by krnbatta** [XeroAPI/xero-oauth2-omniauth-strategy#2]
Hi 
When a user is asked to log in to Xero account, he is asked whether he wishes to connect to an organization. In the dropdown, it shows that old organizations are already connected. Refer image :
<img width="422" alt="Screenshot 2019-11-01 at 4 59 47 AM" src="https://user-images.githubusercontent.com/8068341/67973502-ba0f3a00-fc64-11e9-865e-1300dcc70020.png">

My questions are:
* How to disconnect the user from the organizations?
* How to specify organization in the API? For example, I am using PNL report endpoint: "https://api.xero.com/api.xro/2.0/Reports/ProfitAndLoss?fromDate=2019-10-01&toDate=2019-10-31"
This endpoint is returning report from "Google" only and not from "Yahoo" and "Demo Company". I didn't specify "Google" anywhere. How to specify the organization?

**Comment by adamzuckerberg** [comment]
![disconnect](https://user-images.githubusercontent.com/6652718/67983610-ade69680-fbea-11e9-95bb-d4076758e367.png)

**Comment by adamzuckerberg** [comment]
Looks like you can disconnect from the Xero account.  That may be sufficient unless their docs say we need to add a disconnect on our end.  For QuickBooks, they required it from our end, but Xero might be OK with doing it on Xeros side. There may be a webhook we should subscribe to so that we know it was disconnected, but let's worry about the big stuff first - (A) getting the Pro Forma populated with data, then (B) updating on the 1st of the month, and (C) single sign-on from the Xero account "Get the app" button and (D) clicking on "Connect to Xero" from within the app. Those are the big ones. :)

**Comment by jenksguo** [comment]
Hi @krnbatta,

Please find my responses below: 

> How to disconnect the user from the organizations?
We are currently working on the disconnection endpoint. 
For a complete disconnection, the Xero user will need to disconnect from Xero UI via Organisation > Settings > Connected Apps > Disconnect
![image](https://user-images.githubusercontent.com/41350731/68910312-76104f00-07a5-11ea-8bfa-6f70beafc033.png)

> How to specify organization in the API?
In Xero OAuth 2.0, all API client calls will need to include an access token and tenant id in the header. The list of tenants (which are orgs) are returned in /connections endpoint. 

Read more about it on our OAuth 2.0 documentation: 
https://developer.xero.com/documentation/oauth2/auth-flow

The API call flow is also explained in our DevBlog: 
https://devblog.xero.com/xero-oauth-2-with-ruby-313a6ea37989

Closing this issue as it is a general question on Xero OAuth 2.0 APIs.
